Add pg_ prefix to "scripts" executables
Renamed executables:

- createdb
- dropdb
- createuser
- dropuser
- vacuumdb
- reindexdb

diff --git a/src/test/locale/de_DE.ISO8859-1/runall b/src/test/locale/de_DE.ISO8859-1/runall
--- a/src/test/locale/de_DE.ISO8859-1/runall
+++ b/src/test/locale/de_DE.ISO8859-1/runall
@@ -35,8 +35,8 @@ for f in char varchar text; do
    fi
    echo "Testing PgSQL: sort on $ftype type..."
 
-   dropdb testlocale >/dev/null 2>&1
-   createdb testlocale || abort "createdb failed"
+   pg_dropdb testlocale >/dev/null 2>&1
+   pg_createdb testlocale || abort "createdb failed"
    psql -X -d testlocale -c "CREATE TABLE wordlist (name_en char(20), name_de $ftype);"  >/dev/null 2>&1 || abort "createtable failed"
    psql -X testlocale < test-de.sql.in > test-de-$f.sql.out 2>/dev/null || abort "test query failed"
    diff expected/test-de-$f.sql.out test-de-$f.sql.out
@@ -50,8 +50,8 @@ for f in char varchar text; do
    fi
    echo "Testing PgSQL: upper () on $ftype type..."
 
-   dropdb testlocale >/dev/null 2>&1
-   createdb testlocale || abort "createdb failed"
+   pg_dropdb testlocale >/dev/null 2>&1
+   pg_createdb testlocale || abort "createdb failed"
    psql -X -d testlocale -c "CREATE TABLE wordlist (name_en char(20), name_de $ftype);"  >/dev/null 2>&1 || abort "createtable failed"
    psql -X testlocale < test-de-upper.sql.in > test-de-upper-$f.sql.out 2>/dev/null || abort "test query failed"
    diff expected/test-de-upper-$f.sql.out test-de-upper-$f.sql.out
@@ -60,5 +60,5 @@ done
 echo "Testing PgSQL: select on regexp..."
 psql -X testlocale < test-de-select.sql.in > test-de-select.sql.out 2>/dev/null || abort "select query failed"
 diff expected/test-de-select.sql.out test-de-select.sql.out
-dropdb testlocale || abort "dropdb failed"
+pg_dropdb testlocale || abort "dropdb failed"
 echo "Finished."
diff --git a/src/test/locale/gr_GR.ISO8859-7/runall b/src/test/locale/gr_GR.ISO8859-7/runall
--- a/src/test/locale/gr_GR.ISO8859-7/runall
+++ b/src/test/locale/gr_GR.ISO8859-7/runall
@@ -36,8 +36,8 @@ for f in char varchar text; do
    fi
    echo "Testing PgSQL: sort on $ftype type..."
 
-   dropdb testlocale >/dev/null 2>&1
-   createdb testlocale || abort "createdb failed"
+   pg_dropdb testlocale >/dev/null 2>&1
+   pg_createdb testlocale || abort "createdb failed"
    psql -X -d testlocale -c "CREATE TABLE usastates (abbrev char(2), name_en char(20), name_gr $ftype);"  >/dev/null 2>&1 || abort "createtable failed"
    psql -X testlocale < test-gr.sql.in > test-gr-$f.sql.out 2>/dev/null || abort "test query failed"
    diff expected/test-gr-$f.sql.out test-gr-$f.sql.out
@@ -45,5 +45,5 @@ done
 echo "Testing PgSQL: select on regexp..."
 psql -X testlocale < test-gr-select.sql.in > test-gr-select.sql.out 2>/dev/null || abort "select query failed"
 diff expected/test-gr-select.sql.out test-gr-select.sql.out
-dropdb testlocale || abort "dropdb failed"
+pg_dropdb testlocale || abort "dropdb failed"
 echo "Finished."
diff --git a/src/test/locale/koi8-to-win1251/runall b/src/test/locale/koi8-to-win1251/runall
--- a/src/test/locale/koi8-to-win1251/runall
+++ b/src/test/locale/koi8-to-win1251/runall
@@ -33,8 +33,8 @@ for f in char varchar text; do
    fi
    echo "Testing PgSQL: sort on $ftype type..."
 
-   dropdb testlocale >/dev/null 2>&1
-   createdb testlocale || abort "createdb failed"
+   pg_dropdb testlocale >/dev/null 2>&1
+   pg_createdb testlocale || abort "createdb failed"
    psql -X -d testlocale -c "CREATE TABLE usastates (abbrev char(2), name_en char(20), name_ru $ftype);"  >/dev/null 2>&1 || abort "createtable failed"
    psql -X testlocale < test-koi8.sql.in > test-koi8-$f.sql.out 2>/dev/null || abort "test query failed"
    diff expected/test-koi8-$f.sql.out test-koi8-$f.sql.out
@@ -42,5 +42,5 @@ done
 echo "Testing PgSQL: select on regexp..."
 psql -X testlocale < test-koi8-select.sql.in > test-koi8-select.sql.out 2>/dev/null || abort "select query failed"
 diff expected/test-koi8-select.sql.out test-koi8-select.sql.out
-dropdb testlocale || abort "dropdb failed"
+pg_dropdb testlocale || abort "dropdb failed"
 echo "Finished."
